---
- name: Install Prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - git
    - npm
    - nodejs-legacy
    - nginx
    - python3-pip
  become: yes

- name: stat checkbox location
  stat:
    path: "{{ansible_env.HOME}}/checkbox/"
  register: cb_stat

- name: Remove folder if it exists
  command: rm -rf "{{ansible_env.HOME}}/checkbox/"
  when: cb_stat.stat.exists==True
  become: yes

- name: Clone the checkbox repo
  git:
#    repo: https://github.com/chrisparnin/checkbox.io.git
    repo: 'https://github.com/manushri-singh/checkbox.io.git'
    dest: "{{ansible_env.HOME}}/checkbox/"
    force: yes

- name: Install the forever node package
  npm:
    global: yes
    name: forever
  become: yes

- name: Install the node packages using npm
  npm:
    path: "{{ansible_env.HOME}}/checkbox/server-side/site"

- name: Copy nginx conf file from repo to nginx (part 1)
  fetch:
    src: "{{ansible_env.HOME}}/checkbox/local-conf/nginx.conf"
    dest: "{{lookup('env', 'HOME')}}/nginx.conf"
    flat: yes

- name: Copy nginx conf file from repo to nginx (part 2)
  copy:
    src: "{{lookup('env', 'HOME')}}/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  become: yes

- name: Replace the server root in the "default" file
  replace:
    dest: "{{ansible_env.HOME}}/checkbox/local-conf/default"
    regexp: "root (.)+;"
    replace: "root {{ansible_env.HOME}}/checkbox/public_html/;"

- name: Copy "default" file to nginx sites-available folder (part 1)
  fetch:
    src: "{{ansible_env.HOME}}/checkbox/local-conf/default"
    dest: "{{lookup('env', 'HOME')}}/default"
    flat: yes

- name: Copy "default" file to nginx sites-available folder (part 2)
  copy:
    src: "{{lookup('env', 'HOME')}}/default"
    dest: "/etc/nginx/sites-available/default"
  become: yes

- name: Restarting NGINX
  service:
    name: nginx
    state: restarted
  become: yes
...
