---
- hosts: servers
  roles:
    - initialSetupServer
    - redisSetupMaster

- hosts: clients
  roles:
    - initialSetupClients

- hosts: nomad_instances
  become: yes
  pre_tasks:
  - name: Disable Firewall
    service: name=ufw state=stopped
  - name: Wait for 30 sec
    pause:
      seconds: 30
  roles:   
  - role: brianshumate.nomad
    nomad_bind_address: 0.0.0.0
    nomad_docker_enable: no
  post_tasks:
  - name: Wait for 30 sec
    pause:
      seconds: 30

- hosts: clients
  roles:
  - configNomadClients
  - redisSetupSlave

- hosts: servers
  roles:
  - startNomadJob
...
