---
- hosts: localhost
  roles:
    - createEC2Instance
    - generateInventoryFile

- hosts: localhost
  tasks:
  - name: Install essential packages
    become: yes
    apt: name={{item}} update_cache=yes
    with_items:
    - python-netaddr

  - name: Install Roles
    command: ansible-galaxy install -r requirements.yml
...