---
- name: Install Prerequisites
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python3-pip
  become: yes

- name: Add apt key for mongodb-org
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7F0CEB10
    state: present
  become: yes

- name: Add apt source for mongodb
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse
    state: present
  become: yes

- name: Install mongodb
  apt:
    pkg: mongodb
    state: present
    update_cache: yes
  become: yes

- name: Install pymongo to use with mongodb
  pip:
    name: pymongo
    state: present
  become: yes

- name: Add mongodb user
  mongodb_user:
    database: "{{mongodb_database}}"
    name: "{{mongodb_user}}"
    password: "{{mongodb_pass}}"

- name: Comment out Bind IP in mongodb.conf file
  replace:
    dest: /etc/mongodb.conf
    regexp: '^bind_ip'
    replace: '#bind_ip'
  become: yes

- name: Insert bind IP in mongodb.conf file
  lineinfile:
    path: /etc/mongodb.conf
    insertafter: '^#bind_ip'
    line: 'bind_ip = 0.0.0.0'
  become: yes

- name: Restarting MongoDB
  service:
    name: mongodb
    state: restarted
  become: yes
...