ansible_home_dir: "/home/ubuntu/"

GIT_ID: "{{lookup('env', 'GIT_ID_P')}}"
GIT_TOKEN: "{{lookup('env', 'GIT_TOKEN_P')}}"

aws_access_key: "{{ansible_env.AWS_KEY}}"
aws_secret_key: "{{ansible_env.AWS_SECRET_KEY}}"
aws_region: us-east-2
ami_id: ami-336b4456
instance_type: t2.micro
key_pair: ubuntu-host