- name: Set client agent file
  template:
    src: "client.hcl.j2"
    dest: "/etc/nomad.d/client.hcl"
    mode: 0644
  become: yes

- name: Restart client
  service: 
    name: nomad
    state: restarted
  become: yes

- name: Copy startserver.sh to remote system
  template:
    src: "startserver.sh.j2"
    dest: "{{ansible_env.HOME}}/startserver.sh"
    mode: 0755

- name: Wait for nomad to be restarted
  pause:
    seconds: 20