---
- name: Install the package "npm"
  apt:
    name: npm
    state: present
  become: yes

- name: Create a template xml file for Jenkins checkbox build job
  template: src=build_xml.j2 dest=/tmp/checkbox_temp.xml

- name: Check if job exists
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ list-jobs --username {{jenkins_username}} --password {{jenkins_password}}"
  register: jenkins_cb_stat

- name: create Checkbox jenkins jobs with xml files
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ create-job {{jenkins_checkbox_job_name}} < /tmp/checkbox_temp.xml --username {{jenkins_username}} --password {{jenkins_password}}"
  when: jenkins_cb_stat.stdout.find(jenkins_checkbox_job_name)==-1

- name: Create a template xml file for Jenkins checkbox build job
  template: src=canary_xml.j2 dest=/tmp/checkbox_canary_temp.xml

- name: create Canary Checkbox jenkins jobs with xml files
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ create-job {{jenkins_checkbox_canary_job_name}} < /tmp/checkbox_canary_temp.xml --username {{jenkins_username}} --password {{jenkins_password}}"
  when: jenkins_cb_stat.stdout.find(jenkins_checkbox_canary_job_name)==-1

- name: Remove previous playbook versions
  file:
    path: "{{jenkins_home_dir}}checkbox_deploy"
    state: absent
  become: yes

- name: Copy deployment playbook
  become: yes
  copy:
    src: checkboxDeploy/
    dest: "{{jenkins_home_dir}}checkbox_deploy"
    owner: jenkins

- name: Copy vault pass
  become: yes
  copy:
    src: vault-pass.txt
    dest: "{{jenkins_home_dir}}checkbox_deploy/vault-pass.txt"
    owner: jenkins

- name: Copy inventory for checkbox
  become: yes
  template:
    src: inventory_cb_deploy.yml.j2
    dest: "{{jenkins_home_dir}}checkbox_deploy/inventory_cb_deploy.yml"
    owner: jenkins

- name: Build Jenkins Job for Checkbox_io
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ build {{jenkins_checkbox_job_name}} --username {{jenkins_username}} --password {{jenkins_password}} -s"

- name: Build Canary Jenkins Job for Checkbox_io
  become: yes
  shell: "java -jar {{ jenkins_cli_jar_loc }}/jenkins-cli.jar -s http://{{ jenkins_ip }}:{{ jenkins_port }}/ build {{jenkins_checkbox_canary_job_name}} --username {{jenkins_username}} --password {{jenkins_password}} -s"
