---
- name: Restarting MongoDB
  service:
    name: mongodb
    state: restarted
  become: yes

- name: Restarting NGINX
  service:
    name: nginx
    state: restarted
  become: yes

- name: Starting/Restarting nginx using forever
  shell: cd {{ansible_env.HOME}}/checkbox/server-side/site/; forever stopall; forever start server.js
  environment: "{{env_vars}}"
...
